-- Fixed US 50-state reference list (+ DC), per PRD §9/§44 decision.
-- Small and static enough that the Alpine state-filter combobox (PRD §9)
-- renders it once into the DOM and filters client-side.

create table states (
	code text primary key,
	name text not null,
	sort_order int not null default 0
);

insert into states (code, name, sort_order) values
	('AL', 'Alabama', 1),
	('AK', 'Alaska', 2),
	('AZ', 'Arizona', 3),
	('AR', 'Arkansas', 4),
	('CA', 'California', 5),
	('CO', 'Colorado', 6),
	('CT', 'Connecticut', 7),
	('DE', 'Delaware', 8),
	('DC', 'District of Columbia', 9),
	('FL', 'Florida', 10),
	('GA', 'Georgia', 11),
	('HI', 'Hawaii', 12),
	('ID', 'Idaho', 13),
	('IL', 'Illinois', 14),
	('IN', 'Indiana', 15),
	('IA', 'Iowa', 16),
	('KS', 'Kansas', 17),
	('KY', 'Kentucky', 18),
	('LA', 'Louisiana', 19),
	('ME', 'Maine', 20),
	('MD', 'Maryland', 21),
	('MA', 'Massachusetts', 22),
	('MI', 'Michigan', 23),
	('MN', 'Minnesota', 24),
	('MS', 'Mississippi', 25),
	('MO', 'Missouri', 26),
	('MT', 'Montana', 27),
	('NE', 'Nebraska', 28),
	('NV', 'Nevada', 29),
	('NH', 'New Hampshire', 30),
	('NJ', 'New Jersey', 31),
	('NM', 'New Mexico', 32),
	('NY', 'New York', 33),
	('NC', 'North Carolina', 34),
	('ND', 'North Dakota', 35),
	('OH', 'Ohio', 36),
	('OK', 'Oklahoma', 37),
	('OR', 'Oregon', 38),
	('PA', 'Pennsylvania', 39),
	('RI', 'Rhode Island', 40),
	('SC', 'South Carolina', 41),
	('SD', 'South Dakota', 42),
	('TN', 'Tennessee', 43),
	('TX', 'Texas', 44),
	('UT', 'Utah', 45),
	('VT', 'Vermont', 46),
	('VA', 'Virginia', 47),
	('WA', 'Washington', 48),
	('WV', 'West Virginia', 49),
	('WI', 'Wisconsin', 50),
	('WY', 'Wyoming', 51);
